### ISSUE TITLE
Completely remove created CRUD

### ISSUE THREAD

**Issue by szymon-szychulski** [LaravelDaily/quickadmin#124]
How to completely remove created CRUD?

I removed files from app directory, files from resources/view and CRUD table in database.

But I have an error: 
` Fatal error: Uncaught ReflectionException: Class view does not exist in /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752`

**Comment by ModestasV** [comment]
Hello,

Looking at error - seems like you have something to do with the fact that `view` class is not existing.. Without looking at your code - it is impossible to know what went wrong there.

Deleting the crud has these steps:

- delete database entries
- delete views
- delete models
- delete controllers
- delete custom routes
- remove deleted crud from any relationships you might have

But once again, seems like your issue comes from another angle

**Comment by szymon-szychulski** [comment]
>delete custom routes

where can I found routes from created CRUDs? I don't see this in routes directory. There is in vendor?

**Comment by ModestasV** [comment]
Our routes will be removed automatically, notice the word custom there :) This means that any route you have added that directs to the crud - has to be removed
