### ISSUE TITLE
Too bad that your package is recognized as CSS package

### ISSUE THREAD

**Issue by welcoMattic** [LaravelDaily/quickadmin#59]
May be minify CSS (and JS) solve the problem? ;)

**Comment by ModestasV** [comment]
Hello,

Could you tell us what problem does this cause? There was zero complains about this and we are quite ok with that as long as people know what Quickadmin does.

**Comment by welcoMattic** [comment]
It's not a real problem, but it sounds weird for me to see a Laravel package marked as CSS repo on Github.

**Comment by ModestasV** [comment]
To be honest, this could be caused by the fact that we possibly have way more css/html than php code at this time. I don't think that minifying them would help due the fact that we would need to include non-minified versions too. 

Yes, you are right, minified versions would make the page faster but we are focusing on the back-end not the front end and giving users the right to do whatever they want :) We are just giving this template as an example and some people will keep it, some will change.
