### ISSUE TITLE
Create cagetorys

### ISSUE THREAD

**Issue by mustafabpamuk** [LaravelDaily/quickadmin#68]
Hi,
Do you have a structure that allows you to create categories within categories ?

Thanks

**Comment by mustafabpamuk** [comment]
Hi again,

i solved the problem above. But now i have to ask you something again, there is a download button on the panel in your web site but when i download it. i couldnt see that button in my panel. 

thanks.

**Comment by ModestasV** [comment]
Hello,

If you are talking about our web version, not the package - you are downloading whole project, not generator. This means that you are downloading the files that you can upload to your server and go live. If you need to edit anything - you must visit our page to edit it and download again.

**Comment by mustafabpamuk** [comment]
ok, thnx. 

And i have another question :) i couldnt find a way to upload multiple pictures. Do i have to write a code about it or is there a way i missed? 

thanks.

**Comment by ModestasV** [comment]
We don't have it yet. The problem with multi-upload is that there is way too many usage cases and it would be a potential nightmare to include such system so at this point - you must include it yourself.

We are still working on improvements but we can't promise anything due to the complexity required for this system to work.

**Comment by mustafabpamuk** [comment]
good luck :) ty
