### ISSUE TITLE
Update unique validation issue 

### ISSUE THREAD

**Issue by sshekhawat** [LaravelDaily/quickadmin#84]
Hello 
I have create one section  name is "Category" and category should be unique. Now i add  category then unique validation working fine but when i update then it not working 

For example i have create" mobile " category and now i update this category then show error message " The name has already been taken. " 
i have check rule file 
public function rules()
    {

```
    return [
         'name' => 'required|unique:category,name'.$id, 

    ];
}
```

in this file i need updated id for it, how to get this id on this page my page name and path is 
/var/www/html/laravel/app/Http/Requests/UpdateCategoryRequest.php

**Comment by orrd** [comment]
I'm not sure if I'm following exactly the specifics of what you're trying to do, but see https://laravel.com/docs/5.3/validation#rule-unique.  You don't need to give it $id.  The "unique" validation feature is smart enough to check the database for you.

**Comment by ModestasV** [comment]
@sshekhawat Hey, instead of $id you should use: $this->route('PARAMETER_NAME');

@orrd Hey, Laravel is smart enough to know what to check but to be able to update the entry with the same title - you need to specify an id that has to be excluded. If you don't do this - the problem comes from the logic of how laravel handles the unique check: It simply counts how much entries has the same title and if it is greater than 0 - it will trigger a bad validation. But if you pass an id of the current record - it will be excluded (query will get where id != %s) :)
