### ISSUE TITLE
CK Editor Problem

### ISSUE THREAD

**Issue by Muhammadinaam** [LaravelDaily/quickadmin#97]
![ckeditor1](https://cloud.githubusercontent.com/assets/22542738/21182742/72642772-c226-11e6-8374-47ffe8d21eff.png)

If we click the save button on CK Editor as shown in the image above. The form gets submitted.

Please either remove the save button from CK Editor or prevent it from submitting the main form.

**Comment by ModestasV** [comment]
Hi,
To be fair, I personally think that this is not an issue as it allows to save your form faster. As an example, imagine you are having a blog post form where you enter title and write a post in full screen more. Instead of exiting the full screen mode - you can press this icon and your form will be submitted.
